name: Playwright API Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      # You can re-enable this once GitHub Actions fixes v2/v3:
      # - name: Upload HTML report on failure
      #   if: failure()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: playwright-report
      #     path: playwright-report/

      - name: Publish HTML report to GitHub Pages
        if: always()
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch
          git switch gh-pages
          rm -rf *
          cp -r ../playwright-report/* .
          git add .
          git commit -m "📊 Update Playwright report"
          git push origin gh-pages
